### ISSUE TITLE
create `useContractRead` hook

### ISSUE THREAD

**Issue by LuizAsFight** [FuelLabs/fuels-npm-packs#84]
this hook will need to return the value after reading it from a contract

it will need to create a contract:
```
new Contract(
  address,
  abi,
  provider,
);
```

the inputs for this hook:
```
{ contract, functionName, args }:
{
  contract: Contract | { address: string; abi: Abi };
  functionName: string;
  args: contractInputs[]
```

ps:
- key of query to cache: address + chainId + functionName + args
  - chainId comes from provider.getChainId()
  - also check what wagmi uses as key for contract Read
- execute function from contract.functions[functionName]
- only run function if isReadOnly: true. It means the function does not write to storage
- needs to check if typing of Contract will be correct by itself
  - if not we will need some work on typing to define the return of the function

**Comment by helciofranco** [comment]
![Screenshot 2024-05-29 at 15 25 46](https://github.com/FuelLabs/fuels-npm-packs/assets/7074983/90aadb28-0890-4c0d-b930-4ecfd3616658)

**Comment by arthurgeron** [comment]
We can check if this approach can be useful for inferring a type with the contract's methods using the abi.
https://github.com/FuelLabs/fuel-explorer/blob/67328901a8485643bf5c6477f0cb9411fccf0445/packages/app-portal/src/systems/Chains/eth/services/connectors.ts#L63

**Comment by luizstacio** [comment]
It would be good to provide a contract instance instead of the ABI + contract ID

**Comment by LuizAsFight** [comment]
> It would be good to provide a contract instance instead of the ABI + contract ID

we can have a `useContract` that will return the contract instance, this one is a shortcut for reading the function directly


Ultimately we want to have:
`useContract` -> returns a contract instance
`useContractRead` -> executes a contract method and returns its response
`useContractWrite` -> executes a mutation function in the contract and returns its response
